name: Docker Build and Testing

on:
  push:
    branch:
      - testing-pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout our repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build the Docker image
        run: docker build -t iliterally/service-web-store-devops:55664489/service-web-store-devops

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.NABAZ_USERNAME }} -p ${{ secrets.NABAZ_TOKEN }}

      - name: Push the Docker image to Docker Hub
        run: docker push iliterally/service-web-store-devops:55664489/service-web-store-devops


